version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - karelhala
  allow:
  - dependency-name: "@redhat-cloud-services/frontend*"
  - dependency-name: "@patternfly/*"
    dependency-type: direct
  ignore:
  - dependency-name: "@redhat-cloud-services/frontend-components-config"
    versions:
    - 3.0.0-beta23
    - 4.0.0
    - 4.0.1
    - 4.0.10
    - 4.0.11
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.15
    - 4.0.16
    - 4.0.17
    - 4.0.18
    - 4.0.19
    - 4.0.2
    - 4.0.20
    - 4.0.21
    - 4.0.22
    - 4.0.23
    - 4.0.25
    - 4.0.26
    - 4.0.27
    - 4.0.3
    - 4.0.4
    - 4.0.5
    - 4.0.6
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: "@redhat-cloud-services/frontend-components"
    versions:
    - 3.0.1
    - 3.0.10
    - 3.0.11
    - 3.0.2
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.0.9
    - 3.1.0
    - 3.1.1
    - 3.1.10
    - 3.1.2
    - 3.1.3
    - 3.1.4
    - 3.1.5
    - 3.1.6
    - 3.1.7
    - 3.1.9
  - dependency-name: "@patternfly/react-table"
    versions:
    - 4.20.15
    - 4.23.0
    - 4.23.1
    - 4.23.14
    - 4.23.2
    - 4.24.0
    - 4.24.1
    - 4.26.6
  - dependency-name: "@patternfly/react-core"
    versions:
    - 4.101.3
    - 4.106.1
    - 4.106.2
    - 4.115.1
    - 4.90.2
    - 4.97.0
    - 4.97.1
    - 4.97.2
  - dependency-name: "@redhat-cloud-services/frontend-components-utilities"
    versions:
    - 3.0.2
    - 3.0.3
    - 3.1.0
    - 3.1.1
  - dependency-name: "@redhat-cloud-services/frontend-components-notifications"
    versions:
    - 3.0.2
    - 3.0.3
    - 3.0.4
  - dependency-name: "@patternfly/patternfly"
    versions:
    - 4.80.3
