name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # prerequisite for all jobs, install node modules only once
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # cache node modules for all jobs to use
      - uses: actions/cache@v3
        id: node_modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: install-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm i # use cached modules
  # unit testing job
  test-unit:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - uses: actions/cache@v3
        id: node_modules-cache
        with:
          path: "**/node_modules"
          key: install-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm i
      - run: npm run test -- --coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/clover.xml
  # lint
  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - uses: actions/cache@v3
        id: node_modules-cache
        with:
          path: "**/node_modules"
          key: install-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm i
      - run: npm run lint
  # cypress component testing
  cypress-component:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'      
      # consume installed modules
      - uses: actions/cache@v3
        id: node_modules-cache
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: install-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      # Install dependencies if cache miss
      - if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm i
      # Run Cypress component tests
      - uses: cypress-io/github-action@v6
        with:
            component: true
            install: false
            browser: chrome
